name: Secret HTTP Call

on: [push]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API with Secret
        run: curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://api.example.com/data
